# Generated by Django 5.0.7 on 2024-10-21 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_alter_user_details_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_details',
            name='status',
            field=models.CharField(default='unaccept', max_length=20),
        ),
    ]
