# Generated by Django 5.0.7 on 2024-12-05 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_user_details_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubjectChoices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_code', models.CharField(max_length=20)),
                ('subject_name', models.CharField(max_length=40)),
            ],
        ),
    ]
